feat: add bookings
cpu-fan/java-shareit pull request #2
Opened 2023-03-10 22:08 UTC by cpu-fan

2023-03-12 10:39 UTC, NikolaiDem requested changes

2023-03-12 10:39 UTC, NikolaiDem commented on pom.xml
> +		<dependency>
Зависимость лишняя

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (bookingDto.getEnd().isBefore(bookingDto.getStart())) {
Задача контроллера - только маршрутизировать запрос. Поэтому всю бизнес логику лучше перенести в сервис, а в методе контроллера лишь вызвать метод сервиса.
Аналогично для остальных методов.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +//        Item item = itemService.getItemById(bookingDto.getItemId());
Закомментированный код лучше удалить

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingCreationDto.java
> +public class BookingCreationDto {
Для start и end необходимо добавить NotNull, чтобы в createBooking(...) не возникло NPE

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
В финальном статусе REJECTED тоже нельзя менять статус.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    @Query(value = "select b.id, b.start_date, b.end_date, b.item_id, b.booker_id, b.status " +
Почему запрос native? Можно проще написать через JPQL

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Аннотации FutureOrPresent и Future здесь не обязательны, так как dto не является входящим параметром методов контроллера.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                LocalDateTime startNewBooking = booking.getStart();
LocalDateTime startNewBooking = booking.getStart();
 LocalDateTime endNewBooking = booking.getEnd();
можно вынести до цикла.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>  public class ItemController {
Всю бизнес логику перенести в ItemService

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +            "where i.name ilike ?1 " +
Здесь не хватает скобок : (a or b) && c

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemCreationDto.java
> +public class ItemCreationDto {
Все поля private

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemIdNameDto.java
> +public class ItemIdNameDto {
Все поля private

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne
ManyToOne -  у одного пользователя может быть много предметов

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +public interface BookingService {
Лучше сделать возвращаемыми типами методов сервиса - dto классы, чтобы изменения внутренней модели не отразились на API.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>  public interface ItemService {
Лучше сделать возвращаемыми типами методов сервиса - dto классы, чтобы изменения внутренней модели не отразились на API.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findAll()
Лучше добавить условие, что пользователь является владельцем в сам запрос к БД.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<CommentDto> comments = commentRepository.findByItemId(item.getId()).stream()
Проблема N+1 запроса. Лучше выгрузить все комментарии для всех предметов одним запросом к БД.
Аналогично для получения next и last бронирований.

2023-03-12 10:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//        checkSameEmail(user.getEmail());
Закомментированный код удалить.

2023-03-13 19:26 UTC, cpu-fan commented on src/main/java/ru/practicum/shareit/item/dto/ItemCreationDto.java
> +public class ItemCreationDto {
Хорошо, сделаю) в прошлый раз просто другой ревьюер предложил использовать аннотацию @FieldDefaults )

2023-03-16 07:46 UTC, NikolaiDem requested changes
В UserController здесь "@Valid @PathVariable long userId" Valid лишний. В UserController всю бизнес логику перенести в UserService.  В UserService лучше сделать возвращаемыми типами методов сервиса - dto классы, чтобы изменения внутренней модели не отразились на API.

2023-03-16 07:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    @Query("select b " +
Можно избавиться от явного джойна и перейти к неявному:
@Query("select b " +
            "from Booking b " +
            "where b.item.owner.id = ?1 " +
            "order by b.start desc")

2023-03-16 07:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +            "and is_available is true", nativeQuery = true)
native здесь тоже не обязателен, можно сделать через JPQL

2023-03-16 07:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>  public class UserServiceImpl implements UserService {
Лучше сделать возвращаемыми типами методов сервиса - dto классы, чтобы изменения внутренней модели не отразились на API.

2023-03-16 07:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        .filter(c -> c.getItem().getId() == i.getId())
Из списка comments нужно сделать мапу с ключом Item.id и значением списка комментариев по данному ключу. Таким образом можно избавиться от полного перебора всех комментариев каждый раз.

2023-03-16 22:37 UTC, NikolaiDem approved these changes

2023-03-19 12:36 UTC, merged